import type { Metadata } from "next";
import "@/app/ui/globals.css";
import { alegreya, joseFinSans } from "@/app/ui/fonts";
import { Navigation } from "@/app/ui/Navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${joseFinSans.className} antialiased`}>
        <h1 className={`${alegreya.className} text-5xl p-4 text-center`}>
          Dragon Sanctuary
        </h1>
        <Navigation />
        {children}
      </body>
    </html>
  );
}